# Dependencies
markdown: kramdown
highlighter: pygments

# Permalinks
permalink: pretty
# relative_permalinks: true

# Setup
title: Oscar Palm
tagline: "Msc Student @ Chalmers"
description: "Software engineering student at Chalmers University of Technology"
url: http://oscarpalm.net
baseurl: /

author:
  name: "Oscar Palm"
  url: https://linkedin.com/in/oscar-palm-48362a15a/
  linkedin: https://linkedin.com/in/oscar-palm-48362a15a/
  github: https://github.com/x183

paginate: 5

# Custom vars
version: 0.1.0

github:
  repo: https://github.com/x183/page
